### ISSUE TITLE
TD5 CEJMA Je suis en retard 20/11/23

### ISSUE THREAD

**Issue by eyesonjesusplease** [eyesonjesusplease/BTS-SIO2-2023#14]
Activité : Le règlement européen sur les services numériques (DSA) :
entre en application le 17 février 2024 mais entre en vigueur le 25 août 2023
pour les plus grosses plate-formes.

En vous aidant des informations disponibles avec le lien ci-dessous ou de
vos recherches sur Internet répondez aux questions suivantes :

1. Quel est le principe de base du DSA ?

2. Le DSA s'applique-t-il à toutes les entreprises ?

3. Le DSA est-il une contrainte supplémentaire ou une aide pour les petites entreprises ?

**Comment by whoamitty** [comment]
[TD5_devoir-fait_whoamitty.pdf](https://github.com/whoamitty/BTS-SIO2-2023/files/13413415/TD5_devoir-fait_whoamitty.pdf)
